# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Update package list

on:
  push:
    branches: [ "master" ]

jobs:
  update-package-list:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK ${{ matrix.Java }} 
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.Java }} 
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      id: update
      run: |
        CURRENT_DIR=$(pwd)
        MASTER_REPO_DIR="$CURRENT_DIR/repo"
        NEW_REPO_DIR="$CURRENT_DIR/../newbranch"
        LII_REPO_URL="https://github.com/SmileYik/LuaInMinecraftBukkitII.git"

        # prepare repo
        cp -r $CURRENT_DIR $NEW_REPO_DIR
        cd $NEW_REPO_DIR
        git switch repo || git switch -c repo
        rm -rf *

        # init submodule and copy to new repo dir
        cd $CURRENT_DIR
        git submodule update --init --recursive
        cd $MASTER_REPO_DIR
        find . -type d -name ".git" -exec rm -rf {} +
        cp -r * $NEW_REPO_DIR

        # generate lua package
        git clone $LII_REPO_URL
        cd LuaInMinecraftBukkitII
        git submodule update --init --recursive
        chmod +x ./gradlew
        mkdir run
        echo "eula=true" > run/eula.txt
        luainminecraftbukkit_luacage_build="$NEW_REPO_DIR" ./gradlew runServer -PWorkflow=YES -PTargetJava=${{ matrix.Java }}
        grep -q "org.eu.smileyik.luaInMinecraftBukkitII" ./run/logs/latest.log && { echo "存在报错信息，终止！" >&2; exit 1; }
        cd ..
        if [[ $(git status --porcelain) ]]; then
          echo "changes_made=true" >> $GITHUB_OUTPUT
        else
          echo "changes_made=false" >> $GITHUB_OUTPUT
        fi
        
    # - name: Print luacage.json
    #   if: |
    #     steps.update.outputs.changes_made == 'true'
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y jq
    #     jq . repo/luacage.json
        
    - name: Commit and Push Changes
      if: steps.update.outputs.changes_made == 'true'
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions Bot
        author_email: actions@github.com
        message: 'chore(auto): Auto generate package list'
        cwd: '../newbranch'
        new_branch: "repo"
